// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'web support was removed. You can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'windows support was removed.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxl1ZmaISFckQf4rq2LAOrybADm2apaSo',
    appId: '1:502540128160:android:89fd4da5d2c156adad9ec5',
    messagingSenderId: '502540128160',
    projectId: 'deadshotstack',
    storageBucket: 'deadshotstack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFXeQ9Co6Fr655YPgnbXgcPYiSG3ope0s',
    appId: '1:502540128160:ios:701e9015a7bbe4b7ad9ec5',
    messagingSenderId: '502540128160',
    projectId: 'deadshotstack',
    storageBucket: 'deadshotstack.firebasestorage.app',
    iosBundleId: 'com.example.deadshot',
  );

  // web and windows FirebaseOptions were removed because those apps
  // were deleted from the Firebase console. Access via those
  // platforms will throw UnsupportedError in `currentPlatform`.
}
